# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-08 04:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.CharField(max_length=500)),
                ('shortened_url', models.CharField(max_length=100)),
                ('custom_url', models.CharField(max_length=100)),
                ('visit_count', models.IntegerField()),
                ('shorten_count', models.IntegerField()),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
