# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-08 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='original_url',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='shortened_url',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
